#!/bin/sh
#
# infostrain: Automates the process of
#             setting up conditional PPTP VPN routing
#             for GNU/Linux users of DSi

_restart_networkmanager() {
    echo ╔════════════════════════════════════════
    echo ║ Restarting NetworkManager
    echo ╚════════════════════════════════════════

    systemctl restart NetworkManager 2>/dev/null
    sv restart NetworkManager 2>/dev/null # For runit users
    sleep 10
    nmcli conn up "infostrain_dynamic"
    nmcli conn up "infostrain_vpn"
}

setup_filters() {
    echo ╔════════════════════════════════════════
    echo ║ Setting up filters
    echo ╚════════════════════════════════════════

    profile_path_vpn=/etc/NetworkManager/system-connections/infostrain_vpn.nmconnection
    profile_path_static=/etc/NetworkManager/system-connections/infostrain_static.nmconnection

    dynamic_gateway=$(ip r | grep -Po '.*(?= dev ppp)' | tail -1)
    sed -i \
        "/\[ipv4\]/aignore-auto-routes=true\nroute1=10.0.0.0/8,$dynamic_gateway" \
        "$profile_path_vpn"

    private_ip=$(ip a | grep 'inet.* ppp.*' | awk '{print $2}')
    static_gateway=10.1.0.1
    sed -i \
        "/\[ipv4\]/aaddress1=${private_ip}/24,${static_gateway}" \
        "$profile_path_static"

    _restart_networkmanager
}

setup_aliases() {
    echo ╔════════════════════════════════════════
    echo ║ Setting up aliases
    echo ╚════════════════════════════════════════
    os_user=$(logname)

    cat <<eof >/home/"$os_user"/.bashrc_infostrain
vu(){
    sudo nmcli con up infostrain_dynamic 2> /dev/null
    sudo nmcli con up infostrain_vpn
}

vd(){
    sudo nmcli con down infostrain_vpn
    sudo nmcli con up infostrain_static 2> /dev/null
}
eof

    cat <<eof >>/home/"$os_user"/.bashrc
. .bashrc_infostrain 2> /dev/null
eof

}

initiate_profiles() {
    echo ╔════════════════════════════════════════
    echo ║ Initiating NetworkManager profile
    echo ╚════════════════════════════════════════

    profile_path_vpn=/etc/NetworkManager/system-connections/infostrain_vpn.nmconnection
    profile_path_dynamic=/etc/NetworkManager/system-connections/infostrain_dynamic.nmconnection
    profile_path_static=/etc/NetworkManager/system-connections/infostrain_static.nmconnection

    echo gateway?
    read -r gateway
    echo username?
    read -r username

    stty -echo
    echo password?
    read -r password
    stty echo

    cat <<eof >"$profile_path_vpn"
[connection]
id=infostrain_vpn
type=vpn

[vpn]
gateway=$gateway
password-flags=0
user=$username
service-type=org.freedesktop.NetworkManager.pptp

[vpn-secrets]
password=$password

[ipv4]
dns=10.1.0.26;
method=auto
eof

    cat <<eof >"$profile_path_dynamic"
[connection]
id=infostrain_dynamic
type=ethernet
eof

    cat <<eof >"$profile_path_static"
[connection]
id=infostrain_static
type=ethernet

[ipv4]
dns=10.1.0.26;
method=manual
eof

    chmod u=rw,g=,o= \
        "$profile_path_vpn" \
        "$profile_path_dynamic" \
        "$profile_path_static"
    _restart_networkmanager
}

main() {
    initiate_profiles
    setup_filters
    setup_aliases
}
main
